version: "3.3"

services:
  apollo:
    build: ./graphql
    ports:
      - 8090:4000
    environment:
      - NEO4J_SERVER=neo4j
      - NEO4J_USER=neo4j
      - NEO4J_PASS=testtest
    depends_on:
      - neo4j
      - queue

  neo4j:
    image: neo4j:4.4.4
    restart: always
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-conf:/var/lib/neo4j/conf/
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/testtest
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

  queue:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=rabbitmqpass
    expose:
      - 5672
    ports:
      - 5672:5672
      # - 15672:15672

  celery-beat:
    build: ./tasks
    volumes:
      - ./tasks:/app
    entrypoint: celery -A task beat --loglevel=info
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=rabbitmqpass
      - NEO4J_SERVER=neo4j
      - NEO4J_USER=neo4j
      - NEO4J_PASS=testtest
    depends_on:
      - neo4j
      - queue

  celery-worker:
    build: ./tasks
    volumes:
      - ./tasks:/app
    entrypoint: celery -A task worker --loglevel=info
    depends_on:
      - neo4j
      - queue
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmquser
      - RABBITMQ_DEFAULT_PASS=rabbitmqpass
      - NEO4J_SERVER=neo4j
      - NEO4J_USER=neo4j
      - NEO4J_PASS=testtest

  # flower:
  #     build: ./tasks
  #     volumes:
  #         - ./tasks:/app
  #     ports:
  #         - 5555:5555
  #     expose:
  #         - 5555
  #     entrypoint: flower -A task --port=5555
  #     depends_on:
  #         - queue
  #     environment:
  #         - RABBITMQ_DEFAULT_USER=rabbitmquser
  #         - RABBITMQ_DEFAULT_PASS=rabbitmqpass
